### ISSUE TITLE
aide installation google assistant

### ISSUE THREAD

**Issue by ghost** [Spikharpax/Avatar-Plugin-Google-Assistant#1]
bonjour stephane un aide pour installer le google assistant , jai suivie tout les etape jusque a installer python3, j ai ouvre une fenêtre de commande DOS est taper : python -m pip install --upgrade pip, je suis arriver jusque la le reste je n ai pas compris comment intaller a partir de chapitre 3;
3 - Installez le package google-assistant-sdk:
merci d'avance pour ton aide

**Comment by Spikharpax** [comment]
Tu suis tout simplement la documentation. Tout se fait dans une fenêtre DOS
- Etape 3
python -m pip install --upgrade google-assistant-sdk[samples]
- Etape 4
python -m pip install --upgrade google-auth-oauthlib[tool]
- Générer la clé
google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype --scope https://www.googleapis.com/auth/gcm --save --headless --client-secrets /path/to/credentials.json

**Comment by halimgambit** [comment]
Stephane rebonjour, je te fait mes excuses car je me suis mal exprimer avec le commentaire d'avant , en faite jusque a l'etape 4 c'est bon , c'est a partir de : Générer la clé, que je bloque quand je rentre la commande de generer le clé dans le DOS
aussi pour les 2 clé  : client secret et client  id.json ,  comment faire?, il faut les sauvegarder, renomer et les mettre dans n importe quel repertoire ou les renseigner sur le fichier proprieté du plugin google assistant, bien cordialement
 
Microsoft Windows [version 10.0.18363.720]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\pc>python -m pip install --upgrade pip

C:\Users\pc>python -m pip install --upgrade google-assistant-sdk[samples]

C:\Users\pc>python -m pip install --upgrade google-auth-oauthlib[tool]

C:\Users\pc>
C:\Users\pc>
C:\Users\pc>google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype \
'google-oauthlib-tool' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

google-oauthlib-tool --scope https://www.googleapis.com/auth/assistant-sdk-prototype --scope https://www.googleapis.com/auth/gcm --save --headless --client-secrets /path/to/credentials.json

**Comment by Spikharpax** [comment]
![image](https://user-images.githubusercontent.com/10834317/77188114-cbeb5f80-6ad5-11ea-93bc-6dc19cbe748d.png)

Une simple recherche dans un explorateur t'aurait donné le chemin.
Normalement, à l'installation de python, le répertoire Scripts est mis dans le path mais bon... suivant comment on l'installe, il est évident que si il n'est pas dans le path, tu l'exécutes dans le répertoire ou il se trouve (_cd <Path python/Scripts_  **puis** _google-oauthlib-tool --scope..._)

Sinon,
![image](https://user-images.githubusercontent.com/10834317/77188529-6e0b4780-6ad6-11ea-9b60-5505f8199a36.png)

Je ne sais pas quoi te dire sinon, as-tu ouvert la documentation ? 
Regarde la copie d'écran de la doc juste au dessus, il y a toutes les informations
